DEFRA/waste-carriers-front-office

.env.example, config/mongoid.yml
Previously we had specified each of the parameters that make up a connection to the databases within the `mongoid.yml` file. The documentation for the file is heavily centered on this kind of way of doing it <https://docs.mongodb.com/mongoid/master/tutorials/mongoid-installation/#anatomy-of-a-mongoid-config>.
So database, hosts, user, password etc are all listed out. However commented out is mention of providing a URI which has all the details included. Our web-ops team were pushing for using this format and after some investigation
- it looks like this is how we currently do it for our existing app when running in production
- though not scientific, some investigation online suggests this is the typical way to do it when running in production
So this change is about following conventions …
=> Refactor mongoid config to use URI's

Gemfile, Gemfile.lock, lib/tasks/passenger.rake
https://eaflood.atlassian.net/browse/WC-161
In production we use Passenger as our web application server, as Webrick is not suitable for production deployments.
Passenger as a web application server will handle the HTTP requests, but also manage all processes and resources, and enables administration, monitoring and problem diagnosis. It is used in production because it gives us an ability to scale by creating additional processes, and will automatically restart any that fail.
This change adds it to the project, in such a way that all future calls to `bundle exec rails s` will actually cause Passenger to start and create an instance of the app in a process, rather than firing up webrick.
Because of this and the way processes are isolated they will not automatically pick up code changes. …
=> Add Passenger web app server to project

.gitignore
The Passengerfile.json is used to configure how the web application server we use will run in any      given environment. Because it is environment dependent we don't add it to the source code.
=> Ignore Passengerfile.json

Gemfile, Gemfile.lock
Now that the project is an engine and which we reference in the front-office and back-office apps when developing locally we often need to make changes to this project, which we want to see in the apps when run.
To support this we can use a feature in bundler to tell it that a gem is actually stored locally, rather than always pulling from the original source; `bundle config --local local.my_gem`.
However this option is only supported if a branch has also been defined in the entry. We also believe its useful to specify the branch in the gemfile, so other developers can be clear on what is being referenced in the source repo.
N.B. For more details on local gem config see
https://cruikshanks.co.uk/blog/local-gems-for-local-projects/ …
=> Add branch to WCR renewals Gemfile entry

config/application.rb
https://eaflood.atlassian.net/browse/WC-133
https://eaflood.atlassian.net/browse/WC-161
This change resolves an issue that has arisen when we come to try and deploy the project in our environments (not local dev).
We are using [Capistrano](https://github.com/capistrano/capistrano) to deploy the project onto our servers, and the [Capistrano-rails](https://github.com/capistrano/rails) plugin which handles rails specific tasks. The issue in our case is asset compilation.
When Capistrano is run its from the context of a Jenkins instance, and it is making an ssh call to the target instances. In this case the command its running is `$HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile`. Run in local dev that is fine, but when run in our environment we get an error
```
Caused by: …
```
=> Set secret_key_base when run under prod & rake

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/ability.rb, app/models/user.rb, config/initializers/devise.rb, config/routes.rb, db/seeds.rb, spec/factories/user.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/sessions_spec.rb, spec/support/factory_bot.rb
When we first set up the engine, we included users and related functionality like Devise and CanCanCan. However, it's become clear that the front office and back office users are sufficiently different that we shouldn't be trying to tackle this in the engine and should let the host apps handle it instead.
This PR re-implements the user functionality (including Devise and CanCanCan) which was removed from the engine in DEFRA/waste-carriers-renewals#228
=> Move users out of engine

config/routes.rb
https://eaflood.atlassian.net/browse/WC-427
Currently the waste-carriers-front-office mounts the renewals engine at root. (For example, /renew/CBDU1234).
The new and existing applications will be accessed through the same domain. Determining which requests should go to which applications. This is a lot easier to do if the routes are similar. Mounting the journey within a directory (eg /fo/renew/CBDU1234) means we can cover the whole engine with a single line (eg /fo/*) rather than specifying every single route, which would be time-consuming to set up and maintain.
This change should cover the Devise paths as well.
=> Mount renewals engine in a directory, not root

Gemfile
We ran into some problems with Passenger slowing down our unit tests, so we'll just use it in development and production for now.
=> Use WEBrick in test environment

app/views/shared/_footer.html.erb
Fix links to privacy and cookies policies by using the High Voltage path helper instead of hard-coding the paths.
=> Fix broken footer links

config/application.rb
This is to improve the way we generate WorldPay success and failure URLs in the engine. See https://github.com/DEFRA/waste-carriers-renewals/pull/231
=> Set the host in application config

config/environments/production.rb
We found when running the app in production mode it assumed SSL was being used and would therefore force a redirect to HTTPS. Setting this value to false     would not elicit this behaviour.
However it appears we need to ensure `force_ssl` is enabled to ensure that our cookies are marked as secure. So to make it explicit we are uncommenting this  line and ensuring `force_ssl` is enabled when the app is run in production.
=> Enable force_ssl in production

Gemfile, Gemfile.lock
When we deploy our apps to non-development environments they will normally be deployed to multiple instances, with access controlled by a load balancer.
The load balancer will route requests across the instances, and will essentially 'ping' each one to ensure it is still alive and responding. Should an instance stop responding the LB will no longer route traffic to it until it is up and running again.
Previously we have configured our environments to 'ping' `/version`. This is fine and a relatively light weight page. However it does still hit the rails instance and requires the page to be generated and then the response sent back.
Recently there was some confusion about whether health checks from AWS [Application Load Balancers](https://docs.aws.amazon.com/elasticloadbalancing/latest/appli …
=> Add specific support for ELB health check calls

db/seeds/CBDU200.json, db/seeds/CBDU201.json, db/seeds/CBDU202.json, db/seeds/CBDU203.json, db/seeds/CBDU204.json, db/seeds/CBDU205.json, db/seeds/CBDU206.json, db/seeds/CBDU207.json, db/seeds/CBDU208.json, db/seeds/CBDU209.json, db/seeds/CBDU210.json, db/seeds/CBDU211.json, db/seeds/CBDU212.json, db/seeds/CBDU213.json, db/seeds/CBDU214.json, db/seeds/CBDU215.json, db/seeds/CBDU216.json, db/seeds/CBDU217.json, db/seeds/CBDU218.json, db/seeds/CBDU219.json, db/seeds/CBDU220.json, db/seeds/CBDU221.json, db/seeds/CBDU222.json, db/seeds/CBDU223.json, db/seeds/CBDU224.json, db/seeds/CBDU225.json, db/seeds/CBDU226.json, db/seeds/CBDU227.json, db/seeds/CBDU228.json, db/seeds/users.json
Instead of @waste-exemplar.gov.uk, we use @example.com to show that these won't be government users.
=> Change seed email addresses

spec/factories/address.rb, spec/factories/meta_data.rb, spec/factories/registration.rb, spec/factories/user.rb
factory_bot 4.11.0 deprecates static attributes, which will be removed in v5. This meant that when we ran our test suite, we got a huge number of deprecation warnings. For example:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
expires_on { Fri, 21 Aug 2020 10:11:31 UTC +00:00 }
```
So this commit does exactly that.
For more info, see: https://github.com/thoughtbot/factory_bot/releases/tag/v4.11.0
=> Update deprecated static attributes in factories

lib/tasks/create_transient_registrations.rake
https://eaflood.atlassian.net/browse/WC-145
As part of the design of the new renewals service, when a user comes to renew their registration we take the existing record and generate a transient_registration (a new record) from it.
This is so they can update their details during the renewal process without affecting the existing registration, and retain their existing reg number. Once the process is complete, the transient object switches to being their renewed registration.
However, due to the less structured nature of the database, we cannot assume that all existing upper tier registrations have all the fields, properties and sub documents we might expect. Therefore we need a mechanism to test the conversion from a registration to a transient_registration to ensure it can handle existing …
=> Test converting active upper tier regs to transient objects

.env.example, app/mailers/test_mailer.rb, app/views/test_mailer/test_email.text.erb, config/application.rb, config/environments/development.rb, config/environments/production.rb, lib/tasks/email.rake
https://eaflood.atlassian.net/browse/WC-353
https://eaflood.atlassian.net/browse/WC-354
The engine will be responsible for building emails and triggering when they are sent (see https://github.com/DEFRA/waste-carriers-renewals/pull/261 for implementation of the completed renewal confirmation email). However, as the host applications are sending the emails, they need to be configured to enable this.
=> Configure front-office to send emails via SendGrid

lib/tasks/create_transient_registrations.rake
https://eaflood.atlassian.net/browse/WC-145
When running this task against actual production data we found that it keeps erroring, but at different points. The error is always
```
rake aborted!
Mongo::Error::OperationFailure: cursor id 31540126646 not found (43)
/vagrant/waste-carriers-front-office/lib/tasks/create_transient_registrations.rake:16:in `block in <top (required)>'
/home/vagrant/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/vagrant/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => create_transient_registrations
(See full trace by running task with --trace)
```
Initial Googling seemed to indicate this was caused by a default timeout MongoDb has on cursors of 10  minutes (simply iterating through it does not seem to count as activity). So we trialled changing …
=> Fix reg to trans test to override Mongo timeout

app/controllers/application_controller.rb
https://eaflood.atlassian.net/browse/WC-446
We used this back_button_cache_buster method in the engine to prevent users from accessing forms with now-outdated information using the back button. However, it can also be used to stop people accessing restricted pages after signout by using the back button to access cached pages. So for security reasons, we're implementing it at the ApplicationController level.
=> Stop users accessing pages with back button after signout

config/initializers/secure_headers.rb
https://eaflood.atlassian.net/browse/WC-129
Update our Content Security Policy to allow custom JavaScript variables set up in Google Tag Manager. These variables remove personal identifiable information from URL paths before they are sent to Google Analytics.
We've also enabled beacons as a way of sending a hit to GA, so we need to add a `connect_src` key to our CSP. For more information about this, see: https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms
Note that if we want to use GTM's preview functionality, tagmanager.google.com also needs to be allowed in `script_src` - however I've left this out for now as we should be able to do this testing locally by modifying the CSP as needed, and it won't be needed in …
=> Modify CSP to allow removal of PII in GTM

Gemfile.lock, config/application.rb
https://eaflood.atlassian.net/browse/WC-512
We have added to [Waste-carrier-renewals](https://github.com/DEFRA/waste-carriers-renewals) a 'grace window' which allows users of registrations that have expired to still renew, if the current date is within the window.
However to support this new feature we have to add config to the app which hosts the engine hence this change.
=> Add config for renewal grace window

db/seeds/CBDU212.json, db/seeds/CBDU219.json, db/seeds/CBDU225.json, db/seeds/users.json
Sorry realised that user@mailinator.com was already utilised quite a lot so decided to change to a more specific waste carrier user account. I plan to clean up the emails after use but it didn't feel right sending the emails there.
=> changing email account to less generic name

app/views/dashboards/index.html.erb, config/locales/dashboards.en.yml
https://eaflood.atlassian.net/browse/RUBY-14
If a user has many registrations, the link text for registration actions will be duplicated for each registration. Having multiple links with the same text (eg 'view certificate') on a page isn't good for screenreaders, so we need to make this links unique.
=> Make dashboard links more accessible

app/controllers/dashboards_controller.rb, spec/requests/dashboards_spec.rb
https://eaflood.atlassian.net/browse/RUBY-14
This change is to match the behaviour of the old dashboard in waste-carriers-frontend. Once a user deregisters a registration, they can no longer see it, although it remains in the database for now.
=> Don't list inactive registrations on dashboard

Gemfile, Gemfile.lock
Previously our Gemfiles locked Rails to a specific version (4.2.11). This meant that Dependabot would not prompt us with upgrades. As there is now a critical security patch we'd like to apply, we've decided it's better to accept 4.2.11 and above (within the 4.2 range). This should allow Dependabot to submit PRs for patch-level changes to Rails.
=> Unlock Rails version

app/views/pages/privacy.html.erb
Now that we have a release date, we need to update the 'last updated' privacy policy date to match when the update will actually happen.
=> Update privacy policy date

Gemfile, Gemfile.lock, README.md
We have renamed the engine repo from waste-carriers-renewals to waste-carriers-engine. This commit updates the        Gemfile.
It also updates the content of the README to use the correct name of the application.
=> Switch to new engine repo name

app/views/shared/_footer.html.erb
There is some issue around the fact that bot Devise and HighVoltage are engines, and that we re-define the HighVoltage routes in a third engine, which is the WCR engine. This generate a situation where we are able to either have the route helper be visible with the right engine `:mount` namespace in one place or in the other. 
This have to deal with the login page on front-office, which is managed by Devise, and is using the shared partial object of this PR. 
All other pages using the partial are constructing it correctly, but the Devise page is not. 
Since we have no idea of the cause and we have spent on it a reasonable amount of time already, this is the quick fix we want to merge in order to fix the bug in production.
=> Hardcode pages links

.env.example, config/initializers/waste_carriers_engine.rb
https://eaflood.atlassian.net/browse/RUBY-659
Our experience building Waste Carriers, Waste Exemptions and Flood Risk Activity Exemptions is that they generally share the same validations.
To reduce duplication and help maintenance we built the [defra-ruby-validators](https://github.com/DEFRA/defra-ruby-validators) gem. One of its validators is to confirm that for LTD/LLP organisations the companies house number provided exists and belongs to an active entity.
We've recently incorporated the gem in Waste Carriers, but it expects that at somepoint a call will be made to configure it, because host apps must provide the companies house API key.
After some investigation we've managed to find that we've not done this, which means the validator is not working, which for LTD/LLP users means …
=> Add missing companies house configuration

Gemfile, Gemfile.lock, app/helpers/dashboards_helper.rb, app/models/ability.rb, config/initializers/high_voltage.rb, spec/helpers/dashboards_helper_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-756
Following from: DEFRA/waste-carriers-engine#553
Use RenewingRegistration instead of Transient registration everywhere
=> Use RenewingRegistration instead of TransientRegistration

Gemfile, Gemfile.lock, config/initializers/defra_ruby_mocks.rb, config/routes.rb
We have created a new engine in the DefraRuby namespace called [defra_ruby_mocks](https://github.com/DEFRA/defra-ruby-mocks).
Going forward this will allow us to mock external services like Companies House, and in the future Worldpay.
We only really need to do this when running performance tests. We want to put as much of the service under load as possible, but at the same time we don't want to get into trouble for overloading these external services, or worst case get accused of a DDOS attack.
So by providing an alternate end point that can accept the same request, and return what the service needs, we can replace them when we need to.
For reference we only need to bring mocking support into one app, because we only need one version of the mock endpoint running. And we chose the …
=> Add support for mocking external services

config/initializers/waste_carriers_engine.rb
https://eaflood.atlassian.net/browse/RUBY-817
Prior to this change, though we have an env var that contains the companies house URL it was only needed for the frontend project. The front and back-office projects make use of [defra-ruby-validators(https://.github.com/DEFRA/defra-ruby-validators) for validation of the company registration numbers. It has the URL hardcoded in, though it can be overridden via config.
As it has never changed in our time with these services, the front and back office didn't bother to override it.
Turns out that's an issue when you are trying to replace it with a mock!
So this change is needed to support that. By having the app read the URL from the environment, and then tell the engine this (which in turn tells the validators gem) we can get the front office …
=> Read companies house url from environment

Gemfile, Gemfile.lock, config/application.rb, config/initializers/defra_ruby_mocks.rb
https://eaflood.atlassian.net/browse/RUBY-818
The [defra-ruby-mocks](https://github.com/DEFRA/defra-ruby-mocks) engine that we are using to support mocking external services now supports Worldpay.
This change updates the engine and adds the additional config to allow the front-office to stand in as a mock for Worldpay.
=> Update mocks engine to support Worldpay

Gemfile, Gemfile.lock
https://eaflood.atlassian.net/browse/RUBY-818
Though the mocking we are replacing in [waste-carriers-service](https://github.com/DEFRA/waste-carriers-service) never handled refund requests to Worldpay, we have chosen to include it.
The primary need for mocking the external services is for performance testing, and when we do that we tend to focus on the new and renew registration journeys in the [Waste Carriers Service](https://github.com/DEFRA/ruby-services-team/tree/master/services/wcr).
However it's easy to forget mocking is enabled in an environment, and so it can cause confusion when something suddenly stops working leading to wasted time and effort.
So we have added [support for worldpay refunds](https://github.com/DEFRA/defra-ruby-mocks/pull/14) to our …
=> Update mock engine to get Worldpay refund support

Gemfile, Gemfile.lock, app/helpers/waste_carriers_engine/journey_links_helper.rb, spec/helpers/waste_carriers_engine/journey_links_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-859
We spotted that the 'Finished' button on the 'Renewal complete' and 'Renewal received' buttons was not behaving properly.
This PR overrides the new default engine behaviour to send front office users who click the button to the newer front office dashboard, not the old frontend one.
---
Depends on https://github.com/DEFRA/waste-carriers-engine/pull/647
=> Fix broken 'Finished' link on renewal end pages

Gemfile, Gemfile.lock, config/initializers/waste_carriers_engine.rb
Currently the [Waste Exemptions service](https://github.com/DEFRA/waste-exemptions-engine/pull/112) and the [Waste Carriers Frontend](https://github.com/DEFRA/waste-carriers-frontend/pull/227) have the ability to intercept and play back the details of the last email sent.
This feature is only enabled in our non-production environments and is used as part of our acceptance tests. However our QA @andrewhick has rightly pointed out that the functionality is inconsistent across our services.
Waste Exemptions has it throughout, Waste Carriers only has it in the old app, and Flood Risk Activity Exemptions doesn't have it at all. This makes writing and maintaining acceptance tests across the 3 services difficult and inconsistent so we have been asked to resolve the issue.
Rather than duplicate …
=> Enable defra-ruby-email in the project

app/helpers/dashboards_helper.rb, app/views/dashboards/index.html.erb, spec/helpers/dashboards_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-938
We have built a new 'Cease or Revoke' feature into the back-office to replace the existing 'De-register' and 'Revoke' functions in the old backend.
As part of the rebuild, it was agreed with NCCC that we would not build a version for external users; this would be for internal users only in the future. In fact, it was requested this ability be removed from the external-facing sites because of the issues it causes when users mistakenly 'Delete' their registration.
We forgot to remove the old external 'Delete' link at the time. This change rectifies that oversight.
=> Remove delete link from user dashboard

app/helpers/dashboards_helper.rb, app/views/dashboards/index.html.erb, spec/helpers/dashboards_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-939
We have built a new 'Order copy cards' feature into the back-office to replace the existing 'Order copy cards' feature in the old backend.
As part of the rebuild, it was agreed with NCCC that we would not build a version for external users at this time. Although we have evidence the feature is used, the numbers seem to be marginal so it was agreed we could put off providing an external implementation. This decision made even more sense knowing that the next big changes will be the ability to renew via magic-link, and removal of the account altogether.
Those 2 changes will have a massive impact on the kind of solution that would be needed, so it makes no sense to implement one now only to immediately change it.
NCCC has accepted that all copy …
=> Remove Order copy cards link

Gemfile, Gemfile.lock, config/feature_toggles.yml
https://eaflood.atlassian.net/browse/RUBY-840
We are currently not yet finished with building new registrations into the service (migrating it from the old code). But there are other features we do want to ship so for now, we will hide the ability to start a new registration behind a feature toggle.
=> Hide start new registration behind feature toggle

app/assets/stylesheets/application.scss, app/assets/stylesheets/partials/_govuk-box-highlight.scss
In the new wireframe we have new informative boxes with a background blue. This adds the style that is used by views implemented in the engine.
=> Add style for blue application received box

app/helpers/dashboards_helper.rb, app/views/dashboards/index.html.erb, spec/helpers/dashboards_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-981
The design and implementation of the new 'Edit' feature are based on the fact in the future only NCCC will be doing edits. We have agreed with them to remove this option from external users dashboards, as it is something they would prefer to control. Also, the current version is very poorly designed and implemented and leads to users inadvertently de-registering themselves.
So this change removes the link from the dashboard search results.
=> Remove Edit link from dashboard search results

.travis.yml
Problem: 
Since last week all our builds are failing. 
The main error is:
```
$ gem install -v 1.17.3 bundler --no-rdoc --no-ri
ERROR:  While executing gem ... (OptionParser::InvalidOption)
invalid option: --no-rdoc
The command "gem install -v 1.17.3 bundler --no-rdoc --no-ri" failed and exited with 1 during .
```
Visibile in: https://travis-ci.com/github/DEFRA/waste-exemptions-engine/builds/166643334
The only difference in our builds, seems to be in the binary version of ruby that travis install. Before the breakage, we could observe from the logs that we were installing ruby from https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.4.2.tar.bz2  (https://travis-ci.com/github/DEFRA/waste-exemptions-engine/builds/165727465)
When the breakage started happening, we could observe that the …
=> Remove options from bundler

app/controllers/application_controller.rb, app/views/layouts/application.html.erb
https://eaflood.atlassian.net/browse/RUBY-950
We want to be able to track the performance of the new registration journey and the renewals journey. Because they use the same pages, we'll need a different way to differentiate.
This PR will add a data layer to the front office header. This will be used by Google Tag Manager to send pageviews with the journey as a custom dimension to Google Analytics.
=> Add data layer to head

config/initializers/secure_headers.rb
https://eaflood.atlassian.net/browse/RUBY-1067
We do not want potential attackers to be able to embed our service on other websites, for example in an iframe. So this PR updates our content security policy's frame ancestors setting to block this.
For more info, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
=> Add frame_ancestors settings to CSP

db/seeds/CBDU212.json, db/seeds/CBDU219.json, db/seeds/CBDU225.json, db/seeds/users.json
We are currently [updating the acceptance tests to use the built-in last-email API](https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/315) rather than external services such as mailinator and mailcatcher, so that they run consistently across environments.
The seeded data in this repo also contains references to mailinator, so it makes sense to remove them and update the relevant tests accordingly.
=> Remove references to Mailinator in seeded data

.travis.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/certificates_controller.rb, app/controllers/concerns/can_render_pdf.rb, app/helpers/dashboards_helper.rb, config/routes.rb, spec/factories/meta_data.rb, spec/helpers/dashboards_helper_spec.rb, spec/requests/certificates_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1130
The front office dashboard includes a link to view certificates, but this currently goes to the old frontend.
Since the frontend should be decommissioned before we remove accounts, we'll need to move this feature for now.
This PR adds the ability to view certificates for logged-in users.
=> Allow front office users to view their certificates

app/controllers/passwords_controller.rb, app/helpers/dashboards_helper.rb, app/views/passwords/edit.html.erb, config/locales/en.yml, config/locales/passwords.en.yml, config/routes.rb, spec/helpers/dashboards_helper_spec.rb, spec/requests/passwords_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1129
This previously linked to the password change functionality in the old frontend. It should go to the front office instead.
It turns out that the existing "reset password" function for users who are not logged in could not be reused here - this is specifically for un-authed users, and if you want to use Devise to let logged-in users edit their details, it comes as part of the 'registerable' module. We don't want all of the baggage that comes with that (ie users being able to create their own accounts at will, or edit other account values) so after consulting the docs, the most straightforward option was just to make our own.
Reference: https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-edit-their-password
=> Update dashboard 'change password' link

Gemfile.lock, config/initializers/waste_carriers_engine.rb
https://github.com/DEFRA/defra-ruby-alert/pull/10
With Airbrake changing the name `blacklist` to `blocklist` (quite rightly) we updated our config in defra-ruby-alert so in turn the config in the engine.
This updates the front-office to work with this change.
=> Update defra-ruby-alert to use blocklist

Gemfile.lock
https://eaflood.atlassian.net/browse/RUBY-1154
The link in the page takes you to the frontend where if you are not signed in, you then have to in order to access the link. We don't provide this link on the new 'new registration' done page. It is also our intention to remove accounts in the near future so access to this will be removed anyway.
So this change is just about removing the link in the page to make it consistent with the new registration complete page, and with our future intentions. The change was actually done in the engine as [PR #887](https://github.com/DEFRA/waste-carriers-engine/pull/887). We are just updating the version of the engine to bring the change into the front-office.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
=> Remove link to certificate from renewal complete

app/controllers/passwords_controller.rb, spec/requests/passwords_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1129
When we implemented the password edit in [PR #559](https://github.com/DEFRA/waste-carriers-front-office/pull/559) we had it redirect to root after the POST.
Locally this would redirect to the dashboard. But when testing in AWS it was redirecting to `/fo/start`. When investigating this was because `root_path()` was returning `/` and in our AWS environments if `/fo` is not at the start of the path it will direct the request to the old frontend app.
However, that now also has an automatic redirect to `/fo/start`. So this is why it looks like the change password screen is redirecting to the new registration start screen.
This change tells the passwords controller to redirect to `/fo` after submission. If the user is signed in this will return …
=> Redirect to /fo after password reset

app/helpers/dashboards_helper.rb, spec/helpers/dashboards_helper_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1133
Raised as an issue to do with what happens if a user's session has expired on the old frontend having signed in via it to the front-office. If they then click the 'New registration' button they see a 'Your session has expired' message...or so we have been told 😄
This may indeed be correct though we are currently struggling to replicate it. However, what is definitely wrong is that the 'New registration' button should be directing users directly to the front-office new registration path (`/fo/start`) assuming the `new_registration` feature toggle has been enabled.
It should only direct users to the old app if the feature toggle has not been enabled, which we intend to only happen if some major issue is found with it after release.
So this …
=> Direct 'New registration' btn based on ft. toggle

app/views/layouts/application.html.erb
https://eaflood.atlassian.net/browse/RUBY-1141
As part of https://github.com/DEFRA/waste-carriers-engine/pull/892 I wanted to add the ability to include JavaScript on specific pages.
This change allows us to use `content_for :page_scripts` on individual views and yield it as part of the template. See the engine PR for an example.
=> Allow individual pages to include page_scripts

Gemfile.lock, config/initializers/waste_carriers_engine.rb
https://eaflood.atlassian.net/browse/RUBY-1141
We have come across an issue where we need to change behaviour in the journey based on whether a registration or renewal is being carried out in either the front-office app or the back-office app.
The simplest way we felt to do this was to add a new flag to the config (see [Add host_is_back_office flag to config](https://github.com/DEFRA/waste-carriers-engine/pull/894)) and set it in the initializer.
=> Tell engine we are the front-office

Gemfile.lock
https://eaflood.atlassian.net/browse/RUBY-1141
This updates the front-office to a version of the engine where payment confirmation content is shown based on whether or not it is hosted in the back or front-office.
We have come across an issue where we need to change behaviour in the journey based on whether a registration or renewal is being carried out in either the front-office app or the back-office app.
We should have known, but have just realised that Worldpay does not send payment confirmation emails if the merchant code used is MOTO.
So now we don't show payment confirmation content in the registration and renewal journeys if they are being done from the back-office.
As ar as the front-office is concerned the content is still shown, so the behaviour should not change after this …
=> Update payment confirmation behaviour

Gemfile.lock
https://eaflood.atlassian.net/browse/RUBY-1172
This is the scenario
- User creates a new registration using the new journey in the FO
- User pays by card so a payment confirmation email is taken and :receipt_email is populated
- 3 years later user renews but as AD
Irrespective of how user pays, the renewed registration displays the payment confirmation section in Registration details
As we know that the payment confirmation email is only sent for digital users renewing or creating new registrations its a one-time thing against the registration.
So this means when a new renewal is initialised, we should not be copying the receipt email from the registration as it may not be applicable this time.
This updates the front-office to a version of the engine that ensures `receipt_email` is not …
=> Do not copy receipt_email when init. renewal

app/views/pages/privacy.html.erb
This PR updates the front office privacy policy to match the changes made in https://github.com/DEFRA/waste-carriers-engine/pull/911 , as the changes have not yet been applied to front office.
The date will need to be updated here and on the engine when the RFC is raised.
(Question for a separate PR: why do we need to maintain two identical versions?)
=> Make privacy policy on front office match engine

config/routes.rb, spec/requests/routes_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1221
Since the frontend is being removed and the front office will be reached from the subdomain by default, we need to make some redirects.
The root will now go to /fo/start. Old Devise URLs (eg logging in) will redirect to the updated front office URLs.
Also cleaned up the specs a bit.
=> Redirect old frontend routes to front office pages

Gemfile, Gemfile.lock, spec/support/database_cleaner.rb
We used to use the generic database_cleaner gem but this is now moving in the direction of having ORM-specific gems. ~2.0 updates were failing so it's time to swap.
=> Swap to Mongoid-specific DB-cleaning gem

app/views/pages/cookies.html.erb
https://eaflood.atlassian.net/browse/RUBY-1535
"Cookies that measure website use" and "Strictly necessary cookies" should be the same size.
=> Change size of heading on cookies page

config/application.rb
- `Rails.config.companies_house_host` is used in the `DefraRubyCompaniesHouse` class
https://eaflood.atlassian.net/browse/RUBY-1855
=> Enable mock mode for Rails.config.companies_house_host

.github/workflows/ci.yml
This change forces GitHub CI to run apt-get update before trying to install dependencies. It is currently failing to find the required versions of some ubuntu libraries, possibly because of a stale mirror site. It may be desirable to revert this change in future if the GitHub / ubuntu issue is resolved.
https://eaflood.atlassian.net/browse/RUBY-1254
=> Force GitHub to run apt-get update before installing dependencies

config/application.rb
This change adds Govpay-related environemtn configuration. It also points to the `govpay` branch of the engine.
https://eaflood.atlassian.net/browse/RUBY-1891
https://eaflood.atlassian.net/browse/RUBY-1892
https://eaflood.atlassian.net/browse/RUBY-1893
https://eaflood.atlassian.net/browse/RUBY-1894
=> Govpay MVP WIP

Gemfile, Gemfile.lock
This corrects the engine branch to main instead of govpay.
https://eaflood.atlassian.net/browse/RUBY-2117
=> Use main engine branch

Gemfile.lock, spec/factories/address.rb
This reverts the address_line1 etc naming convention to address_line_1 to align with the format expected by Notify.
https://eaflood.atlassian.net/browse/RUBY-2142
=> Fix address lines

Gemfile.lock, config/application.rb
This change aligns Govpay API token configuration naming with the engine and back-office changes for Govpay refunds.
https://eaflood.atlassian.net/browse/RUBY-2341
=> Update Govpay API token settings

Gemfile.lock
Use the latest version of the `defra_ruby_mocks` gem.
https://eaflood.atlassian.net/browse/RUBY-2433
=> Bump defra_ruby_mocks
