app/views/pages/cookies.html.erb
Content update for cookies page
=> WC-356 Cookies page update

config/application.rb
https://eaflood.atlassian.net/browse/WC-123
Update the application config to include the value we want to save for metaData.route.
See https://github.com/DEFRA/waste-carriers-renewals/pull/236 for details.
=> Set config value for metaData.route

db/seeds/CBDU207.json
I've changed the companies house number to cause a conviction check flag.
=> changing registration seed data to cause conviction flag

.env.example, app/views/layouts/application.html.erb
Add GA code to application so that we can track visits and dropoffs.
https://eaflood.atlassian.net/browse/WC-459
=> Setup GA for project using the GOOGLE_TAGMANAGER_ID environment variable

db/seeds/CBDU233.json
Additional seed data for expired registration
=> adding CBDU233 seed data

db/seeds/CBDU212.json, db/seeds/CBDU219.json, db/seeds/CBDU225.json, db/seeds/users.json
Adding another test account for external email testing using the mailinator service https://mailinator.com
=> Adding user account and test data for email testing

app/views/dashboards/index.html.erb
This will make it much easier for us to run acceptance tests which rely on links for specific registrations.
=> Add unique ID to div around each registration

app/assets/stylesheets/partials/_dashboard.scss, app/assets/stylesheets/partials/_pagination.scss, app/views/dashboards/index.html.erb
- added the section break pattern to replace border
- cleaned up the dashboard scss
- added bottom margin to pagination nav element to provide the button with more visual affordance
=> cleaned up layout, linted scss

app/assets/stylesheets/partials/_dashboard.scss
https://eaflood.atlassian.net/browse/RUBY-14
This adds the same margin to the line break as is given to the following elements - making everything line up. I also refactored the partial to make use of sass nesting.
=> Fixed line width and refactored related sass partial

app/assets/stylesheets/application.scss, app/assets/stylesheets/partials/_published_dates.scss, app/views/pages/privacy.html.erb
https://eaflood.atlassian.net/browse/RUBY-4
We have a revised privacy policy which contains additional information about what we do with the information our users give us.
=> Update privacy policy

app/views/pages/privacy.html.erb
https://eaflood.atlassian.net/browse/RUBY-4
This PR fixes a few small issue in the privacy policy which was raised during QA.
=> Change 'don't' to 'do not'

spec/support/database_cleaner.rb
Following on: https://github.com/DEFRA/waste-carriers-back-office/pull/322/files
This adds DB cleaner configuration to clean the DB around every scenario.
=> Make sure the DB is in a clean status at every scenario run

app/models/user.rb
https://eaflood.atlassian.net/browse/RUBY-381
Generally we want to avoid leaving TODOs around the code, but the next person who works on this should be aware of past decisions about it.
=> Add a comment about session invalidation

app/views/pages/accessibility.html.erb, app/views/shared/_footer.html.erb
From: https://eaflood.atlassian.net/browse/RUBY-607
Add accessibility statement page and link it from the footer.
=> Add accessibility statement page and footer link

app/views/pages/accessibility.html.erb, app/views/shared/_footer.html.erb
From: https://eaflood.atlassian.net/browse/RUBY-607
=> Remove GMT and fix links to accessibility statement

app/views/pages/privacy.html.erb
We now have a confirmed RFC date so know when this will be updated in production.
=> Update privacy policy date

app/views/pages/accessibility.html.erb
Accessibility statement update for https://eaflood.atlassian.net/browse/RUBY-1304
=> Accessibility statement update

app/views/pages/accessibility.html.erb
Accessibility statement service name update
=> Accessibility statement service name update

Gemfile, Gemfile.lock, app/controllers/cookies_controller.rb, app/views/cookies/_action_confirmed.html.erb, app/views/cookies/_action_required.html.erb, app/views/cookies/_banner.html.erb, app/views/layouts/application.html.erb, config/initializers/inflections.rb, config/locales/en.yml, config/routes.rb, spec/features/cookies_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1533
=> Add the updated cookie consent banner

app/views/cookies/_action_confirmed.html.erb, app/views/cookies/_action_required.html.erb, spec/features/cookies_spec.rb
***Fix broken link to 'View cookies'***
https://eaflood.atlassian.net/browse/RUBY-1534
***Link to cookies page in the same window***
https://eaflood.atlassian.net/browse/RUBY-1534
=> Design System: Bug fixes and issues

app/views/pages/cookies.html.erb, config/locales/cookies.en.yml, spec/features/cookies_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1695
=> Update cookies page

config/locales/cookies.en.yml
https://eaflood.atlassian.net/browse/RUBY-1695?focusedCommentId=354438
=> Update sesssion cookie expiration text

Gemfile, Gemfile.lock, db/seeds.rb, db/seeds/CBDU235.json, db/seeds/CBDU236.json, db/seeds/CBDU237.json
- Here we add three registrations that are more than 7 years old and
one of ceased/revoked/expired
Relates to:
https://eaflood.atlassian.net/browse/RUBY-1683
=> Update seeds to include 'deletable' registrations

.github/workflows/brakeman-analysis.yml, Gemfile.lock, README.md
Hakiri is being retired so this is to add Brakeman to our CI pipeline
https://eaflood.atlassian.net/browse/RUBY-1738
=> Enable Brakeman for security scanning

Gemfile.lock
Use the develop branch of the engine
=> Use the develop branch of the engine

Gemfile, Gemfile.lock, config/application.rb
This points the govpay branch of the front-office at the govpay branch of the engine.
=> Use govpay branch of engine

Gemfile, Gemfile.lock, config/application.rb
Bump the engine version to get additional debug information in the front-office log
=> Bump engine version

Gemfile, Gemfile.lock, config/application.rb, config/initializers/defra_ruby_mocks.rb
Bump engine and govpay mocks versions
=> Bump engine and govpay mocks versions

CHANGELOG.md
=> Version 1.13.1

Gemfile, Gemfile.lock, config/application.rb, config/initializers/defra_ruby_mocks.rb
This change merges the long-running govpay branch into main.
https://eaflood.atlassian.net/browse/RUBY-2117
=> Merge govpay branch into main

Gemfile, Gemfile.lock
Add the webrick gem for non-production use
=> Add webrick gem for development

Gemfile, Gemfile.lock
Add the net-imap and net-pop gems.
=> Fix startup

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2234
=> Release v1.13.3

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-1992
=> Release v1.13.4

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2274
=> Release v1.13.5

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2332
=> Release v1.13.6

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2443
=> Version 1.14.1

Gemfile, Gemfile.lock, config/environments/production.rb
Use puma in development to work with govpay mocks v2.4.2
https://eaflood.atlassian.net/browse/RUBY-2433
=> Puma in dev

spec/support/simplecov.rb
Setting up json formatter for simplecov
=> Setting up json formatter for simplecov

Gemfile.lock, app/assets/config/manifest.js
This is to resolve an asset compilation issue in the local vagrant environment.
https://eaflood.atlassian.net/browse/RUBY-2771
=> Add example_card.jpg to manifest

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2751
=> Version 1.18.0

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3019
=> Release v1.19.2

app/views/pages/accessibility.html.erb
Accessibility statement update to align with full compliance
=> RUBY-3026 Accessibility statement update 

.github/workflows/ci.yml, Gemfile.lock, config/mongoid.yml
https://eaflood.atlassian.net/browse/RUBY-2973
=> Configure test DB as a replica set

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3094
=> Version 1.20.2

Gemfile.lock, spec/factories/registration.rb
https://eaflood.atlassian.net/browse/RUBY-3409
=> Align with engine registered_address changes

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3581
=> Version 1.24.2

.rubocop.yml, Gemfile.lock, config/application.rb
https://eaflood.atlassian.net/browse/RUBY-3459
=> Use TaggedLogging

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3651
=> Release v1.24.3

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3679
=> Version 1.25.0

Gemfile, Gemfile.lock
https://eaflood.atlassian.net/browse/RUBY-3894
=> apply govuk-frontend update

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3746
=> Version 1.27.0

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3966
=> Version 1.27.1

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3972
=> Version 1.28.0
